export const TAB_ROUTE = {
    NOW_PLAYING: 'NOW PLAYING',
    POPULAR: 'POPULAR',
    TOP_RATED: 'TOP RATED',
    UPCOMING: 'UPCOMING',
  };
  
  export const SCREEN = {
    TAB_SCREEN: 'TAB SCREEN',
    MOVIE_ITEM_SCREEN: 'MOVIE ITEM SCREEN',
    MOVIE_SEARCH_SCREEN: 'MOVIE SEARCH SCREEN',
    AUTHENTICATION_WEB_VIEW_SCREEN: 'AUTHENTICATION_WEB_VIEW_SCREEN',
    FAVORITES_SCREEN: 'FAVORITES SCREEN',
  };
  